name: CI/CD

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          
      - name: Install dependencies Build
        run: dotnet restore ./src/webapi-serverless/webapi-serverless.csproj
        
      - name: Build
        run: dotnet build ./src/webapi-serverless/webapi-serverless.csproj --configuration Release
      
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./src/web-api-serverless/bin/Release/net6.0/
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: .
          
      - name: Install AWS CLI
        run: dotnet tool install -g Amazon.Lambda.Tools
      
      - name: Deploy to AWS Lambda
        run: dotnet lambda deploy-serverless -sn webapi-serverless -sb code-pipeline-serveless-dotnet -t serverless.template --region us-east-1